name: My test workflow

on:
  push:
    branches:
      - main
    paths:
      - 'gradle.properties'

env:
  COMMIT_MESSAGE: |
    Update Baseline Profile

    Created by GitHub Action [${{ github.workflow }} #${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

    ACLOVERRIDE CODEOWNEROVERRIDE CUSTOMVALIDATIONSOVERRIDE

jobs:
  update-badge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get previous version
        id: get-previous-version
        run: |
          commit_hashes=$(git rev-list -n 5 origin/main -- gradle.properties)
          echo "Commit hashes: $commit_hashes"
    
          second_last_commit_hash=$(echo "$commit_hashes" | tail -n 3)
          echo "Second-to-last commit hash: $second_last_commit_hash"
    
          previous_version=$(git show $second_last_commit_hash:gradle.properties | grep '^version' | cut -d= -f2 | tr -d '[:space:]')
          echo "data: $(git show $second_last_commit_hash:gradle.properties)"
          echo "Previous version: $previous_version"
          echo "::set-output name=prev_version::$previous_version"

      - name: Get current version
        id: get-current-version
        run: |
          echo "::set-output name=current_version::$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')"

      - name: Check for version change
        run: |
          echo "Previous version: ${{ steps.get-previous-version.outputs.prev_version }}"
          echo "Current version: ${{ steps.get-current-version.outputs.current_version }}"
          if [ "${{ steps.get-previous-version.outputs.prev_version }}" = "${{ steps.get-current-version.outputs.current_version }}" ]; then
            echo "No version change. Exiting workflow."
            exit 0
          fi

      - name: Update README Badge
        run: |
          version=$(grep '^version' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          sed -i "s/\(badge\/version-v[0-9]\.[0-9]-blue\.svg\)/badge\/version-v$version-blue.svg/" README.md
          cat README.md

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: github-actions/readme-update
          delete-branch: true
          author: ${{ github.actor }} <${{ github.actor }}@linkedin.com>
          title: 'Update readme'
          body: ${{ env.COMMIT_MESSAGE }}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Turn On PR Auto-Merge
        run: |
          gh pr merge --squash --auto
          --repo ${{ github.repository }}
          ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete branch
        run: |
          git push origin --delete github-actions/readme-update
